parameters:
    evolution7_grunt_usemin.twig.grunt_usemin_extension.class: Evolution7\GruntUseminBundle\Twig\GruntUseminExtension

services:
    evolution7_grunt_usemin.twig.grunt_extension:
        class: %evolution7_grunt_usemin.twig.grunt_usemin_extension.class%
        arguments:
            - @service_container
            - %evolution7_grunt_usemin.dev_path%
            - %evolution7_grunt_usemin.prod_path%
        tags:
            - { name: twig.extension }
